name: CI/CD Pipeline

# Trigger workflow on push to master/main or when PR is made to any branch except master/main
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"
    # Optionally exclude PRs from master/main by adding condition
    # to only run for branches other than master/main
    # example:
    # if: github.head_ref != 'main' && github.head_ref != 'master'

jobs:
  # Job to run linting and tests
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Use your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV # Set PYTHONPATH dynamically

      - name: Install Pylint
        run: |
          pip install pylint

      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py')  # Lint all Python files in the repo

      - name: Run Tests
        run: |
          pytest

  # Job to deploy the app (only on push to main/master)
  deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test # Ensure lint and tests are passed before deploying
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' # Only deploy on push to master or main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Use your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build App
        run: |
          # Example build steps (adjust according to your app)
          echo "Building the app..."

      - name: Deploy to Server
        run: |
          # Add your deployment commands here (e.g., SSH, Docker, etc.)
          echo "Deploying to production server..."
