name: CI/CD Pipeline

# Trigger workflow on push to main/master or on any PR
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "*"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wmctrl x11-utils libxcomposite-dev libxrender-dev

      # - name: Run Tests
      #   run: |
      #     pytest

  deploy:
    needs: lint_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wmctrl x11-utils libxcomposite-dev libxrender-dev

      - name: Build App
        run: |
          echo "Building the app..."
          # e.g. pyinstaller scripts/build_exe.sh

      - name: Deploy FastAPI app with Uvicorn
        run: |
          nohup uvicorn xtend.server:app \
            --host 0.0.0.0 \
            --port 8000 \
            --workers 4 \
            &>/dev/null &
